### ISSUE TITLE
[CLOSED] MacOSX compilation

### ISSUE THREAD

**Issue by devernay** [NatronGitHub/Natron#2]
<a href="https://github.com/predat"><img src="https://avatars3.githubusercontent.com/u/90415?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [predat](https://github.com/predat)**
_Tuesday Oct 22, 2013 at 09:33 GMT_
_Originally opened as https://github.com/MrKepzie/Natron/issues/2_

----

I'm trying to compile on macosx 10.8 with Xcode 5 and libs install with brew.
OpenExr libs installed is v2.0.1.
The compiler (clang) stop with this message:

```
Readers/ExrDecoder.cpp:207:13: warning: deleting pointer to incomplete type 'Imf::InputFile' may cause undefined behavior [-Wdelete-incomplete]
            delete _inputfile;
            ^      ~~~~~~~~~~
Readers/ExrDecoder.h:27:11: note: forward declaration of 'Imf::InputFile'
    class InputFile;
          ^
Readers/ExrDecoder.cpp:209:26: error: allocation of incomplete type 'Imf::InputFile'
        _inputfile = new Imf::InputFile(ba.constData());
                         ^~~~~~~~~~~~~~
Readers/ExrDecoder.h:27:11: note: forward declaration of 'Imf::InputFile'
    class InputFile;
          ^
Readers/ExrDecoder.cpp:251:57: error: member access into incomplete type 'Imf::InputFile'
        const Imf::ChannelList& imfchannels = _inputfile->header().channels();
                                                        ^
Readers/ExrDecoder.h:27:11: note: forward declaration of 'Imf::InputFile'
    class InputFile;
          ^
Readers/ExrDecoder.cpp:289:49: error: member access into incomplete type 'Imf::InputFile'
        const Imath::Box2i& datawin = _inputfile->header().dataWindow();
                                                ^
Readers/ExrDecoder.h:27:11: note: forward declaration of 'Imf::InputFile'
    class InputFile;
          ^
Readers/ExrDecoder.cpp:290:49: error: member access into incomplete type 'Imf::InputFile'
        const Imath::Box2i& dispwin = _inputfile->header().displayWindow();
                                                ^
Readers/ExrDecoder.h:27:11: note: forward declaration of 'Imf::InputFile'
    class InputFile;
          ^
Readers/ExrDecoder.cpp:301:35: error: member access into incomplete type 'Imf::InputFile'
        double aspect = _inputfile->header().pixelAspectRatio();
                                  ^
Readers/ExrDecoder.h:27:11: note: forward declaration of 'Imf::InputFile'
    class InputFile;
          ^
Readers/ExrDecoder.cpp:324:9: warning: deleting pointer to incomplete type 'Imf::InputFile' may cause undefined behavior [-Wdelete-incomplete]
        delete _inputfile;
        ^      ~~~~~~~~~~
Readers/ExrDecoder.h:27:11: note: forward declaration of 'Imf::InputFile'
    class InputFile;
          ^
Readers/ExrDecoder.cpp:350:5: warning: deleting pointer to incomplete type 'Imf::InputFile' may cause undefined behavior [-Wdelete-incomplete]
    delete _inputfile;
    ^      ~~~~~~~~~~
Readers/ExrDecoder.h:27:11: note: forward declaration of 'Imf::InputFile'
    class InputFile;
          ^
Readers/ExrDecoder.cpp:355:45: error: member access into incomplete type 'Imf::InputFile'
    const Imath::Box2i& dispwin = _inputfile->header().displayWindow();
                                            ^
Readers/ExrDecoder.h:27:11: note: forward declaration of 'Imf::InputFile'
    class InputFile;
          ^
Readers/ExrDecoder.cpp:356:45: error: member access into incomplete type 'Imf::InputFile'
    const Imath::Box2i& datawin = _inputfile->header().dataWindow();
                                            ^
Readers/ExrDecoder.h:27:11: note: forward declaration of 'Imf::InputFile'
    class InputFile;
          ^
Readers/ExrDecoder.cpp:398:23: error: member access into incomplete type 'Imf::InputFile'
            _inputfile->setFrameBuffer(fbuf);
                      ^
Readers/ExrDecoder.h:27:11: note: forward declaration of 'Imf::InputFile'
    class InputFile;
          ^
Readers/ExrDecoder.cpp:399:23: error: member access into incomplete type 'Imf::InputFile'
            _inputfile->readPixels(exrY);
                      ^
Readers/ExrDecoder.h:27:11: note: forward declaration of 'Imf::InputFile'
    class InputFile;
          ^
3 warnings and 9 errors generated.
make: *** [build_Powiter/release/.obj/ExrDecoder.o] Error 1
```

**Comment by devernay** [comment]
<a href="https://github.com/MrKepzie"><img src="https://avatars3.githubusercontent.com/u/4058448?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [MrKepzie](https://github.com/MrKepzie)**
_Tuesday Oct 22, 2013 at 09:38 GMT_

----

We don't use OpenEXR 2.0 + features for now, try using a pre 2.0 OpenEXR version even though this should work, what version of Qt do you have and which compiler the Xcode project is using ? ( Build Settings -> Build options -> Compiler for C/C++ / Objective-C)

Alex

**Comment by devernay** [comment]
<a href="https://github.com/predat"><img src="https://avatars3.githubusercontent.com/u/90415?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [predat](https://github.com/predat)**
_Tuesday Oct 22, 2013 at 09:49 GMT_

----

I'm compiling from command line using Clang (Apple LLVM version 5.0 (clang-500.2.75) (based on LLVM 3.3svn)). I don't use Xcode IDE... Qt is 4.8.5.

**Comment by devernay** [comment]
<a href="https://github.com/predat"><img src="https://avatars3.githubusercontent.com/u/90415?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [predat](https://github.com/predat)**
_Tuesday Oct 22, 2013 at 09:58 GMT_

----

The Dropbox download link in 'INSTALL_OSX.txt' is corrupt...

**Comment by devernay** [comment]
<a href="https://github.com/MrKepzie"><img src="https://avatars3.githubusercontent.com/u/4058448?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [MrKepzie](https://github.com/MrKepzie)**
_Tuesday Oct 22, 2013 at 10:01 GMT_

----

Try installing OpenEXR pre 2.0  (1.7.1 ) from  home-brew  or http://www.openexr.com/downloads.html 
I'm going to fix right now the forward declaration in the header file and push that

Alex

**Comment by devernay** [comment]
<a href="https://github.com/MrKepzie"><img src="https://avatars3.githubusercontent.com/u/4058448?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [MrKepzie](https://github.com/MrKepzie)**
_Tuesday Oct 22, 2013 at 10:06 GMT_

----

Aight I just fixed this, try pulling the master branch and re-compiling

**Comment by devernay** [comment]
<a href="https://github.com/predat"><img src="https://avatars3.githubusercontent.com/u/90415?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [predat](https://github.com/predat)**
_Tuesday Oct 22, 2013 at 10:16 GMT_

----

Ok, fine... Powiter start !!!
Is it possible right now to load OFX plugin ? or not implemeted ?

**Comment by devernay** [comment]
<a href="https://github.com/MrKepzie"><img src="https://avatars3.githubusercontent.com/u/4058448?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [MrKepzie](https://github.com/MrKepzie)**
_Tuesday Oct 22, 2013 at 10:22 GMT_

----

Yeah lots of OFX plugins works except the ones with involving time (i.e: Retimer etc…)

You can find a list of plugins here: 

http://devernay.free.fr/hacks/openfx/

You can install the TuttleOFX plugins suite. This is a set of Open-source OFX plugins. They almost all work within Powiter. 

Otherwise commercial OFX plugins work as-well (Sapphire etc…)

Alex

**Comment by devernay** [comment]
<a href="https://github.com/MrKepzie"><img src="https://avatars3.githubusercontent.com/u/4058448?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [MrKepzie](https://github.com/MrKepzie)**
_Tuesday Oct 22, 2013 at 10:26 GMT_

----

Bear in mind that since the software has not yet been released a lot of changes will come soon, for example the project file format is not going to stay as it is, so I don't recommend saving projects right now. 

When the first release will come out, then it will be fully safe and you'll not have to worry for the lifetime of your projects.

Alex

**Comment by devernay** [comment]
<a href="https://github.com/predat"><img src="https://avatars3.githubusercontent.com/u/90415?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [predat](https://github.com/predat)**
_Tuesday Oct 22, 2013 at 10:32 GMT_

----

How do i specify OFX plugins location to Powiter ?

**Comment by devernay** [comment]
<a href="https://github.com/MrKepzie"><img src="https://avatars3.githubusercontent.com/u/4058448?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [MrKepzie](https://github.com/MrKepzie)**
_Tuesday Oct 22, 2013 at 10:34 GMT_

----

you don't have to: by default on OSX, OpenFX plug-ins should be located in  
/Libary/OFX/Plugins/

If you put them in there, Powiter will load them.
